# Generated by Django 2.2.1 on 2019-07-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penname', models.CharField(max_length=100)),
                ('profileimage', models.ImageField(upload_to='profileimages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.UserModel')),
            ],
        ),
    ]
