# Generated by Django 2.2.1 on 2019-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190708_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeatures',
            name='profileimage',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
